services:
    _defaults:
        autoconfigure: true
        autowire: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Agentur1601com\UsedReport\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Tests,Kernel.php,Resources}'

    Agentur1601com\UsedReport\EventListener\CheckImageStatusListener:
        public: true


